### ISSUE TITLE
Sugestão: Identificação de bónus das estações

### ISSUE THREAD

**Issue by DanielAgostinho** [rt-evil-inc/gira#1]
Sugestão: Adicionar elemento visual (cor, símbolo, texto) que permita identificar as estações que tem mais de 70% das docas ocupadas e as que tem menos de 30% de docas ocupadas.

**Comment by ttmx** [comment]
Existe mesmo quem ande de gira por pontos ainda? Sinto que adicionaria muito visual clutter, com benefícios pequeninos. 
Que achas?

**Comment by DanielAgostinho** [comment]
Pessoalmente, as viagens que faço são entre zonas bem servidas, com algumas estações em volta. Geralmente, existe uma ou outra estação que tenha algum bonus e não prejudica o objetivo da viagem. Se for muita informação, podia-se ativar apenas apartir de um nivel de zoom ou por opções no menu de configurações. But its your app.

**Comment by santos-samuel** [comment]
Aproveito a sugestão para reforçar esta ideia, não pelo bónus, mas para facilmente perceber o número de docas livres que existe numa estação de destino.
Não há nenhuma maneira imediata de perceber se a estação para onde queremos ir está ou não cheia e qual o estado das estações à volta (sem abrir o menu de cada uma manualmente).
Indiretamente está relacionado com o bónus, mas na verdade o propósito é outro.

**Comment by rodrigohpalmeirim** [comment]
Durante uma viagem, os pontos das estações mostram o número de docas livres em vez do número de bicicletas disponíveis. A única situação que não está prevista é o caso de se querer saber o número de docas livres antes de começar a viagem, mas diria que, quando é esse o caso, o utilizador já tem uma estação específica em mente e portanto teria de selecionar apenas uma estação para ver a disponibilidade.

Dito isto, eu acho a sugestão boa, mas está dependente de conseguirmos encontrar bom UI para representar o nível de preenchimento das estações no mapa. Fazer o ponto encher consoante o nível não é bom UI porque não permite distinguir a estação selecionada das outras e porque os números ficariam mais difíceis de ler. Talvez uma borda que se fosse preenchendo à volta do ponto?
Nenhuma destas soluções permite mostrar com precisão se o bónus vai ser atribuído ou não, mas considero isso secundário.
Teremos um designer a estudar o assunto.
