### ISSUE TITLE
Desbloquear a gira a distância

### ISSUE THREAD

**Issue by dgelinho** [rt-evil-inc/gira#10]
Sinceramente eu gostaria que desse para desbloquear qualquer gira de qualquer posto sem estar propriamente perto da estação.

A minha dúvida é que eu já desbloqueia gira de muito longe e funcionou, e já tentei outras vezes e não resultou.

Por isso não sei se o bug é não funcionar para tirar giras de estações distantes OU conseguir tirar giras em estações distantes mesmo não sendo o propósito.

A minha sugestão é que se desbloquear gira a distância for um bug eu sugiro colocar essa funcionalidade porque seria sinceramente muito útil (pelo menos para mim😅).

**Comment by rodrigohpalmeirim** [comment]
O desbloqueio à distância já é uma funcionalidade que está implementada! No menu configurações pode ser desativada a opção de limitar o desbloqueio a 35 metros. Esta opção existe apenas para quem quer evitar desbloqueios acidentais em estações que estão longe e está ativa por default.

Não existe qualquer diferença na forma de desbloquear bicicletas perto ou longe. Seria possível explicitar o que é que aconteceu exatamente quando o desbloqueio "não resultou"? Houve alguma mensagem de erro?
