### ISSUE TITLE
Introduzir conceito de pagamento 

### ISSUE THREAD

**Issue by gmatosferreira** [rt-evil-inc/gira#11]
Era bom termos a funcionalidade de pagar com pontos integrada no feedback da viagem, à semelhança do que acontece na app oficial.

Até poderia haver uma configuração no perfil em que pudéssemos definir que por defeito queremos pagar com pontos, para evitar esquecimentos ou erros.

Atualmente uso a +Gira para tudo, mas quando quero pagar lá tenho de voltar à app da EMEL...

Fica a sugestão também de podermos ver o valor de cada viagem no histórico.

**Comment by ttmx** [comment]
A aplicação já paga com pontos quando necessário, ou deveria pagar.
Há algo que não conseguimos controlar, que é a possibilidade de a aplicação não ser aberta a tempo de pagar com pontos.
Haverá no futuro maior transparência com este tipo de pagamentos na aplicação, apenas não houve ainda tempo.

Fico muito contente de usares a aplicação! :)
