### ISSUE TITLE
Gira APIs might stop working in the future

### ISSUE THREAD

**Issue by ilyaluk** [rt-evil-inc/gira#22]
Hey folks, kudos for creating an alternative client for Gira! I'm the author of https://github.com/ilyaluk/girabot, which is also a Gira client, but as a [Telegram bot](https://t.me/BetterGiraBot) (check it out if you use TG 🙂).

Anyway, just a heads up about some changes in Gira APIs:

Previously, APIs were available at `https://apigira.emel.pt/graphql` and `https://api-auth.emel.pt`. Yesterday I noticed that `apigira.emel.pt` became unavailable with unexpected connection resets and TLS errors. I suspect that EMEL folks are "securing" their APIs and made some changes in their infra and recent versions of the app. Here's what I found out from the Android app version 3.4.0 (released 17th of October):

New endpoints:
* `https://egira-proxy-arqetk5clq-ew.a.run.app/api/graphql`
* `wss://egira-proxy-arqetk5clq-ew.a.run.app/ws/graphql`
* `https://egira-proxy-arqetk5clq-ew.a.run.app/auth`

(https://github.com/ilyaluk/girabot/commit/10ad3b06cb1bd6b81a8f10c82db2c4811bdefdfc)

However, there's a catch: now `/api/graphql` requires to include not only `authorization` header with bearer token from their Auth API, but also `x-firebase-token` header with a fresh token from [Firebase App Check](https://firebase.google.com/docs/app-check). `/ws/graphql` and `/auth` APIs don't require these tokens as of now.

What's worse is that the firebase token requires a valid verification of untampered device (via Google Play Integrity on Android or DeviceCheck on iOS). I was able to bypass the Play Integrity on my test Android phone and disable SSL checks in their app to intercept these new APIs and headers. However, I'm not yet sure how to obtain a valid App Check tokens for new endpoints on the server.

Today I noticed that they rolled back the changes on `apigira.emel.pt`, and it's working as before, but I could assume that in the future they will proceed with disabling old endpoints.

Maybe we should contact EMEL to get their position on alternative clients? This change seems to target us and not improve user experience of their app (and probably even worsens the UX for regular users, who's unlucky to not pass device integrity checks or use old app versions).

P.S, fun fact: there's a `file:///Users/luistavares/Desktop/Repositorios/egira-legacy-mobile-app/gira/.dart_tool/flutter_build/dart_plugin_registrant.dart` string left in the build, which might suggest that they are working on a new, non-legacy version of the mobile app.

**Comment by rodrigohpalmeirim** [comment]
Hi! I don't use Telegram, but your project looks cool!

Thanks a lot for the heads up! We were also already investigating this. It's reassuring to know that more people are on the lookout. :)
It seems to me like the only way to obtain the tokens would be through the official app. We're getting started on a way to obtain the tokens and we'll keep you posted.

It's still unclear to me why they rolled back the changes today... Maybe they were just testing? But why would they revert back if the tests were successful? Maybe they weren't successful. Maybe they got complaints from people whose devices stopped being compatible with their app. Who knows...

I think it's really sad that they're investing so much money into blocking our clients. They chose the equivalent of a nuclear weapon to defend the exclusivity of a bike sharing app which should be open-source in the first place. Can't get much more ridiculous than this. The worst part is that, by doing this, they're harming themselves and their users in the process since many people with devices that simply aren't compatible with the app attestation process will stop being able to use the official app. All this to block open-source clients made by people that are actually attempting to contribute to the user experience. I really don't understand what they have to gain from this.

So, in response to if we should contact EMEL regarding their position on this: I think that they've already made it pretty clear.
For now we'll be focusing on working around these roadblocks and improving our app so that it's good enough to release on the Play Store and App Store, and hope that it gains enough traction so that people will start getting mad if EMEL keeps acting like this.
Either way, we will always be open to constructive attempts coming from EMEL's side.

P.S.: A new official app is long overdue! I just think that it would be a waste of money to make a new one from scratch when this project already exists and it's open-source under the GPL-3.0 license. They could just spend way less money and help us improve this one.

**Comment by ilyaluk** [comment]
Welp, they started returning 403 on old endpoint.

```
% % curl -H 'User-Agent: Gira/3.2.8 (Android 34)' https://apigira.emel.pt/graphql
<!doctype html><meta charset="utf-8"><meta name=viewport content="width=device-width, initial-scale=1"><title>403</title>403 Forbidden
```

Damn, I hoped that they would keep it alive for some time

**Comment by ilyaluk** [comment]
Hey @rodrigohpalmeirim, looks great! Can I use the same firebase token source?

**Comment by rodrigohpalmeirim** [comment]
I was just now writing to say that you can feel free to use it!

**Comment by ilyaluk** [comment]
Thank you very much!

If you need any help with the token source itself — feel free to reach out to me at ilya(at)luk.moe, I guess I was doing the same, but had less time during the week.

**Comment by rodrigohpalmeirim** [comment]
I get you, I've also been struggling with time to dedicate to this issue...
It would be great to add some redundancy to the source!
I'll send you some more info later.

**Comment by paixaoPTX** [comment]
@ilyaluk I am sharing this news from May 2024 just as a reminder of what was already anticipated to happen:
https://lisboaparapessoas.pt/2024/05/15/emel-melhorar-aplicacao-gira-terceiros/

"Upgrade of the GIRA Mobile App aimed at analysing and addressing potential security issues on both iOS and Android, as well as in the backend APIs that support it. The current solution should be assessed, with consideration given to immediate mitigation to secure communication by shielding services behind a protected architecture. This approach should safeguard the GIRA App and GIRA services, while ensuring stability and an optimal user experience."

As a regular user, I can only express my gratitude to all the developers involved for their effort and volunteer work, which greatly eased my daily life while these alternative routes were available.

I know this may not be the appropriate place, but perhaps it would be timely to foster some civic mobilisation to potentially reverse or modify the situation. Raising awareness with EMEL about the difficulties posed to everyone by the exclusive use of the official app could be beneficial (even today, I gave up and walked after repeatedly trying to unlock bikes in the official app, with the frustrating 5 min. wait between attempts).

**Comment by mluisbrown** [comment]
I'm not sure how you are generating the Firebase App Check token, maybe using the official Gira App? But I don't think this is a sustainable solution in the long term. App Attestation, when done properly, is very difficult to get around.
They can easily make the token have a very short expiry time (you can check it here: https://fusionauth.io/dev-tools/jwt-decoder) to the point where it will be impractical to be constantly updating the token for this app. 

To be clear, I am really disappointed that EMEL has taken this path. The Gira+ app is so much better than the official one.

**Comment by rodrigohpalmeirim** [comment]
@paixaoPTX It makes me really happy to hear that something we made eased your daily life :)

> "This approach should safeguard the GIRA App and GIRA services, while ensuring stability and an optimal user experience."

The only thing they're "safeguarding" is the exclusivity of their unmaintained and unstable app, while the users seem to prefer the alternative open-source apps.

I agree that we should bring attention to this situation. We will wait a bit until this stabilizes, but our current plans are to publish to the Play Store and App Store soon and I have no doubts that it will help sensitize people to the problem.

**Comment by rodrigohpalmeirim** [comment]
@mluisbrown
> I'm not sure how you are generating the Firebase App Check token, maybe using the official Gira App? But I don't think this is a sustainable solution in the long term. App Attestation, when done properly, is very difficult to get around. They can easily make the token have a very short expiry time (you can check it here: https://fusionauth.io/dev-tools/jwt-decoder) to the point where it will be impractical to be constantly updating the token for this app.

They can't make the tokens have a short expiry time because there is a limit of 10,000 integrity checks per day on the Play Integrity API. App attestation can be difficult to get around, but it isn't designed for this purpose. App attestation is designed for very specific, high-security, infrequent requests, not for *all* the requests of a bike-sharing app, so they will have to make compromises which ultimately will either not impose any significant restrictions to alternative clients or significantly harm their service.

**Comment by getzze** [comment]
I'm also a regular user with LineageOS and since Wednesday I cannot use Gira anymore, a service I paid for with a subscription and with my taxes.
So thanks a lot for your work, you are fantastic!

**Comment by cyberastr4l** [comment]
I've updated the App trough the actions and I'm still unable to login, is the app fully fixed or are you guys still working on reverse engineering the new APIs?

**Comment by rodrigohpalmeirim** [comment]
@cyberastr4l
> I've updated the App trough the actions and I'm still unable to login, I click on the login button and nothing happens, I can see from Rethink app (DNS and Firewall app) that the app is communicating with an IP but nothing happens in the app. Is the app fully fixed or are you guys still working on reverse engineering the new APIs?

Sorry, I was testing on a browser with CORS blocking disabled and didn't even think that they could have changed the policy on their endpoints. Turns out they changed it on their auth endpoint. Try it with the latest commit! This time I've tested it properly ;)

**Comment by mluisbrown** [comment]
@rodrigohpalmeirim I just tried it on iOS with the fix above and it's working great now 👍 Was having the same issue (nothing happens with login button) before.

**Comment by cyberastr4l** [comment]
> @cyberastr4l
> > I've updated the App trough the actions and I'm still unable to login, I click on the login button and nothing happens, I can see from Rethink app (DNS and Firewall app) that the app is communicating with an IP but nothing happens in the app. Is the app fully fixed or are you guys still working on reverse engineering the new APIs?
> 
> Sorry, I was testing on a browser with CORS blocking disabled and didn't even think that they could have changed the policy on their endpoints. Turns out they changed it on their auth endpoint. Try it with the latest commit! This time I've tested it properly ;)

Just tried it and it's working fine. Just a question @rodrigohpalmeirim , I've noticed a disabled station and if I click on it on the map it shows the bikes that are on that station, can I unlock them even when the station is locked? And can I unlock the bikes that are red on the dock?

**Comment by rodrigohpalmeirim** [comment]
@cyberastr4l
> Just tried it and it's working fine. Just a question @rodrigohpalmeirim , I've noticed a disabled station and if I click on it on the map it shows the bikes that are on that station, can I unlock them even when the station is locked? And can I unlock the bikes that are red on the dock?

Could you open a new issue for this, please? Just so it doesn't get confusing and people with the same question can find it easily.

**Comment by cyberastr4l** [comment]
The app is broken again. Talked to @ilyaluk and he said something about the device ID being used to get the token getting banned. EMEL is really a pain in the ass, all of this and they still can't fix their app....

**Comment by rodrigohpalmeirim** [comment]
> The app is broken again. Talked to @ilyaluk and he said something about the device ID being used to get the token getting banned. EMEL is really a pain in the ass, all of this and they still can't fix their app.... 

It's back up again. It was just due to instability on my setup. I'll try to improve it, but ideally we should add some redundancy to avoid this issue entirely.

The device ID is somewhat easy to rotate so that shouldn't be a problem.

**Comment by cyberastr4l** [comment]
Can confirm it is, just checked and all good. 
How are you able to rotate the device ID easily?

**Comment by rodrigohpalmeirim** [comment]
Send me an email and I can give you more info.

**Comment by cyberastr4l** [comment]
@rodrigohpalmeirim Sent you one to the email available in your bio.

**Comment by cyberastr4l** [comment]
@rodrigohpalmeirim App is loading forever again, mGira says it's API Error 401. Can you take a look at it, I think it's token problems again.
