### ISSUE TITLE
Deixou de funcionar

### ISSUE THREAD

**Issue by joaosilva444** [rt-evil-inc/gira#24]
Uso a app há algum tempo e sempre funcionou na perfeição mas agora há cerca de uma semana dps de fazer o login fica a pensar eternamente. Está-vos a acontecer o mesmo?

**Comment by rodrigohpalmeirim** [comment]
Já funciona novamente com o último commit. Estamos a preparar uma nova versão.
Em suma, a EMEL está a tentar bloquear o API deles, mas já arranjámos solução. Para mais informação: ver #22.
